In [0]:
import keras
import pandas as pd
import numpy as np
from sklearn import preprocessing
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/tic-tac-toe/tic-tac-toe.data"
ds = pd.read_csv(url)

ds.head()

x x.1 x.2 x.3  o o.1 x.4 o.2 o.3  positive
0  x   x   x   x  o   o   o   x   o  positive
1  x   x   x   x  o   o   o   o   x  positive
2  x   x   x   x  o   o   o   b   b  positive
3  x   x   x   x  o   o   b   o   b  positive
4  x   x   x   x  o   o   b   b   o  positive

In [0]:
x = ds.iloc[:, :9].values
print(x[0:10])
y = ds['positive'].values
print(y[0:10])


[['x' 'x' 'x' 'x' 'o' 'o' 'o' 'x' 'o']
 ['x' 'x' 'x' 'x' 'o' 'o' 'o' 'o' 'x']
 ['x' 'x' 'x' 'x' 'o' 'o' 'o' 'b' 'b']
 ['x' 'x' 'x' 'x' 'o' 'o' 'b' 'o' 'b']
 ['x' 'x' 'x' 'x' 'o' 'o' 'b' 'b' 'o']
 ['x' 'x' 'x' 'x' 'o' 'b' 'o' 'o' 'b']
 ['x' 'x' 'x' 'x' 'o' 'b' 'o' 'b' 'o']
 ['x' 'x' 'x' 'x' 'o' 'b' 'b' 'o' 'o']
 ['x' 'x' 'x' 'x' 'b' 'o' 'o' 'o' 'b']
 ['x' 'x' 'x' 'x' 'b' 'o' 'o' 'b' 'o']]
['positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive']


In [0]:

le = preprocessing.LabelEncoder()
for _ in range(9):
  x[:,_] = le.fit_transform(x[:,_])
print(x) 

[[2 2 2 ... 1 2 1]
 [2 2 2 ... 1 1 2]
 [2 2 2 ... 1 0 0]
 ...
 [1 2 1 ... 2 1 2]
 [1 2 1 ... 2 1 2]
 [1 1 2 ... 1 2 2]]


In [0]:
y = le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [0]:

one_hot = preprocessing.OneHotEncoder(categorical_features = [0,1,2,3,4,5,6,7,8])
x = one_hot.fit_transform(x).toarray()
x = np.delete(x, [0,3,6,9,12,15,18,21,24], axis=1)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
model = Sequential()
model.add(Dense(9, activation='relu', input_dim=18))
model.add(Dense(9, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
765/765 [==============================] - 1s 729us/step - loss: 0.6507 - acc: 0.6523
Epoch 2/100
765/765 [==============================] - 0s 106us/step - loss: 0.6220 - acc: 0.6575
Epoch 3/100
765/765 [==============================] - 0s 106us/step - loss: 0.6003 - acc: 0.6641
Epoch 4/100
765/765 [==============================] - 0s 108us/step - loss: 0.5803 - acc: 0.6693
Epoch 5/100
765/765 [==============================] - 0s 110us/step - loss: 0.5606 - acc: 0.6902
Epoch 6/100
765/765 [==============================] - 0s 112us/step - loss: 0.5422 - acc: 0.7346
Epoch 7/100
765/765 [==============================] - 0s 111us/step - loss: 0.5249 - acc: 0.7438
Epoch 8/100
765/765 [==============================] - 0s 106us/step - loss: 0.5092 - acc: 0.7621
Epoch 9/100
765/765 [==============================] - 0s 107us/step - loss: 0.4907 - acc: 0.7660
Epoch 10/100
765/765 [==============================] - 0s 112us/step - loss: 0.4730 - acc: 0.7752
Epoch 11/100
765/76

In [0]:
model.save('tictac.h5')

In [0]:
from keras.models import load_model
model1 = load_model('tictac.h5')

In [0]:
y_pred = model1.predict(x_test)
print(y_pred)

[[1.53392553e-04]
 [9.84738588e-01]
 [9.98849034e-01]
 [1.20997429e-05]
 [1.27041340e-03]
 [9.96400356e-01]
 [9.94406343e-01]
 [9.83775616e-01]
 [8.18408370e-01]
 [1.97546482e-02]
 [9.67717767e-01]
 [9.99934733e-01]
 [9.99927938e-01]
 [7.30706513e-01]
 [9.87885058e-01]
 [9.96032417e-01]
 [9.99711752e-01]
 [9.86914515e-01]
 [4.27365303e-05]
 [5.77145815e-03]
 [1.74871087e-03]
 [9.46375072e-01]
 [5.92368841e-03]
 [9.92180347e-01]
 [1.59269571e-03]
 [9.92389679e-01]
 [9.60094571e-01]
 [9.99284148e-01]
 [8.97907197e-01]
 [9.99097645e-01]
 [9.99969661e-01]
 [9.85187888e-01]
 [9.99635816e-01]
 [9.99280453e-01]
 [1.26430392e-03]
 [5.55068254e-04]
 [9.92208719e-01]
 [9.99538898e-01]
 [9.99982119e-01]
 [2.27987766e-05]
 [9.99943495e-01]
 [9.99232888e-01]
 [4.77522612e-04]
 [7.45683908e-04]
 [9.90266204e-01]
 [8.28185380e-02]
 [9.98338580e-01]
 [9.99924779e-01]
 [9.06586647e-05]
 [3.50668132e-02]
 [1.07077062e-02]
 [4.69982624e-04]
 [9.91111517e-01]
 [9.90970254e-01]
 [9.89084542e-01]
 [9.997309

In [0]:
print(x_test)

[[1. 0. 1. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 1. 1. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]]
